Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -10,5 +10,36 @@ pipeline
        checkout scm
      }
    }
+   stage("static_analysis")
+   {
+        cd /Users/srikar.nallapu/.jenkins/workspace/$JOB_NAME
+        mkdir static_code1
+        IFS=' ' read -r -a array <<< "$names"
+        for i in "${array[@]}"
+        do
+  	        IFS='/' read -r -a array1 <<< "$i"
+	          path=""
+	          p="/"
+	          temp=${#array1[@]}
+            temp=$temp-1
+            for index in "${!array1[@]}"
+            do
+                if [ $index == $temp ]
+                then 
+                  cp  $path${array1[index]} ./static_code1/$path${array1[index]}
+
+                else
+                    mkdir /Users/srikar.nallapu/.jenkins/workspace/$JOB_NAME/static_code1/$path${array1[index]}
+                    path=$path${array1[index]}$p
+                fi
+
+            done 
+          done
+          export PATH=/usr/local/bin
+          cd /Users/srikar.nallapu/.jenkins/workspace/$JOB_NAME
+          eslint  -f json -c /Users/srikar.nallapu/.jenkins/workspace/static_config.json  "./**" -o /Users/srikar.nallapu/.jenkins/workspace/$JOB_NAME/result.json || echo "lint failed but continiung the process"
+          export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
+          npm install request
+   }
   }
 }
