Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -12,7 +12,7 @@ pipeline
    }
    stage("static_analysis")
    {
-        cd /Users/srikar.nallapu/.jenkins/workspace/$JOB_NAME
+        cd $JENKINS_HOME/workspace/$JOB_NAME
         mkdir static_code1
         IFS=' ' read -r -a array <<< "$names"
         for i in "${array[@]}"
@@ -29,7 +29,7 @@ pipeline
                   cp  $path${array1[index]} ./static_code1/$path${array1[index]}
 
                 else
-                    mkdir /Users/srikar.nallapu/.jenkins/workspace/$JOB_NAME/static_code1/$path${array1[index]}
+                    mkdir $JENKINS_HOME/workspace/$JOB_NAME/static_code1/$path${array1[index]}
                     path=$path${array1[index]}$p
                 fi
 
@@ -37,7 +37,7 @@ pipeline
           done
           export PATH=/usr/local/bin
           cd /Users/srikar.nallapu/.jenkins/workspace/$JOB_NAME
-          eslint  -f json -c /Users/srikar.nallapu/.jenkins/workspace/static_config.json  "./**" -o /Users/srikar.nallapu/.jenkins/workspace/$JOB_NAME/result.json || echo "lint failed but continiung the process"
+          eslint  -f json -c $JENKINS_HOME/workspace/static_config.json  "./**" -o $JENKINS_HOME/workspace/$JOB_NAME/result.json || echo "lint failed but continiung the process"
           export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
           npm install request
    }
